"""Create user and recipe models

Revision ID: 739fff1b2c0d
Revises: bf0d1eeef33c
Create Date: 2024-10-22 20:05:01.305405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739fff1b2c0d'
down_revision = 'bf0d1eeef33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
